# Generated by Django 3.0.7 on 2020-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrySignup',
            fields=[
                ('bank_name', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('district', models.CharField(max_length=122)),
                ('branch', models.CharField(max_length=122)),
                ('contact', models.IntegerField()),
                ('ifsc', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('micr', models.IntegerField()),
            ],
        ),
    ]
